import type { FoodType, MealTime } from "./types";

export const FOOD_TYPES: FoodType[] = [
  "Phở",
  "Bánh Mì",
  "Gỏi Cuốn",
  "Chả Giò",
  "Nem Rán",
  "Bún Chả",
  "Bún Bò Huế",
  "Cơm Tấm",
  "Cao Lầu",
  "Bánh Cuốn",
  "Bánh Xèo",
  "Bánh Khọt",
  "Bún Đậu Mắm Tôm",
  "Bánh Bao",
  "Xôi",
  "Bún Riêu",
  "Bò Kho",
  "Nem Nướng",
  "Bánh Tráng Nướng",
  "Bánh Bèo",
  "Bánh Canh",
  "Bánh Mì Xíu Mại",
  "Bún Thịt Nướng",
  "Mì Quảng",
  "Hủ Tiếu",
  "Cơm Gà",
  "Cơm Chiên",
  "Bún Mắm",
  "Cháo Lòng",
  "Ốc",
  "Lẩu",
  "Trà Sữa",
  "Cà Phê",
  "Chè",
];

export const MEAL_TIMES: MealTime[] = ["Sáng", "Trưa", "Chiều", "Tối", "Khuya"];

export const HCM_DISTRICTS = [
  "Quận 1",
  "Quận 3",
  "Quận 4",
  "Quận 5",
  "Quận 6",
  "Quận 7",
  "Quận 8",
  "Quận 10",
  "Quận 11",
  "Quận 12",
  "Bình Thạnh",
  "Gò Vấp",
  "Phú Nhuận",
  "Tân Bình",
  "Tân Phú",
  "Bình Tân",
  "Thủ Đức",
  "Hóc Môn",
  "Củ Chi",
  "Nhà Bè",
  "Bình Chánh",
  "Cần Giờ",
];
